
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NE = 18;
  public static final int LT = 13;
  public static final int MULTIPLY = 11;
  public static final int SEMICOLON = 19;
  public static final int ELSE = 3;
  public static final int PLUS = 9;
  public static final int RPAREN = 22;
  public static final int INT = 4;
  public static final int LCURL = 25;
  public static final int WHILE = 7;
  public static final int RETURN = 5;
  public static final int ERROR = 29;
  public static final int IF = 2;
  public static final int LPAREN = 21;
  public static final int GT = 15;
  public static final int ID = 27;
  public static final int LE = 14;
  public static final int NUM = 28;
  public static final int COMMA = 20;
  public static final int EOF = 0;
  public static final int DIVIDE = 12;
  public static final int LSQUARE = 23;
  public static final int GE = 16;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int EQ = 17;
  public static final int ASSIGN = 8;
  public static final int RSQUARE = 24;
  public static final int RCURL = 26;
  public static final int VOID = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "LT",
  "LE",
  "GT",
  "GE",
  "EQ",
  "NE",
  "SEMICOLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LSQUARE",
  "RSQUARE",
  "LCURL",
  "RCURL",
  "ID",
  "NUM",
  "ERROR"
  };
}

